### ISSUE TITLE
UPPER CASE letters in session name seem to block session

### ISSUE THREAD

**Issue by EnidKapelsen** [Chatmosphere/chatmosphere-app#13]
When creating a new session after the update, I noticed that session name"HelloBerlin" would not work (Chrome, Firefox), whereas "helloberlin" works.

## Expected Behavior
I can use upper case as well as lower case to create a session name

## Current Behavior
Names with Uper Cases trigger a blank screen.

## Possible Solution
no clue

## Steps to Reproduce
1. Visit our internal build
2. Type in HelloBerlin or Lunch
2. See a blank screen
3. Try again with helloberlin or lunch

**Comment by dkgrieshammer** [comment]
Should be fixed with 0.6.0
