### ISSUE TITLE
User feedback testing Chatmosphere for use in education

### ISSUE THREAD

**Issue by sampaccoud** [Chatmosphere/chatmosphere-app#19]
First of all congratulations for this amazing app. We loved the demo and installed it on our servers with the intention to test it in contexts of education.

Here are some feedback from our team, not final users yet. As you will see, some issues would be quite problematic in production but we can already imagine what chatmosphere will be in a few months :clap:  We would like to help build it:

- When we tested with >30 users, several users could not be heard. We found out that muting and unmuting was resolving the issue. It is stressful if you are not sure to be heard each time you speak.
- The fact that faces can superpose was disturbing for many. We would expect bubbles to be solid and bump into each other, or at least that a person who speaks would be brought to the foreground.
- The volume going to zero at a certain radius was disturbing with 2 main critics:
        - When you talk, it's difficult to realize who could really hear you, and who couldn't. We think the volume between 2 persons should vary in the same way as it does in real life: decrease slowly with the distance and go to zero only if there is a wall in the obstacle in the background, but not otherwise.
        - When you are talking with one person on your left and one person on your right, both of them can hear you, and you can hear both of them but they cannot hear each other. This also doesn't feel natural.
- Security issues with the related Jisti instance: if a user connects to the same room on the Jitsi server, he/she can see and hear everybody in the Chatmosphere discussion, but no one sees him/her from the Chatmosphere room. It allows spying on a conversation without being seen :scream: 
- People had difficulty understanding that the cats icons meant "muted". Lack of explanations maybe?
- We are unable to join a room without a webcam (e.g. no webcam detected by the browser). We can see that it's also a feature and that talking to plain blue bubbles is not an option... but maybe if you don't have a webcam you could be forced to upload an avatar?
- Keyboard shortcuts to mute/unmute are missing (very helpful in Jitsi)
- Mute is removed when you move your sphere
- Chatmosphere would be a great tool for education with a few additional features (that could also be interesting for a generic usage):
        * organizer status for the teachers,
        * a loudspeaker feature so that the organizer (or other participants when allowed) can be heard all across the board,
        * The ability to build rooms in the background, the walls of which would cut the sound to outside users, 
        * Groups that can be sent to a corner of the board by the organizer in one click (or to rooms as in the previous point). An organizer could randomly assign participants to groups or build groups manually,
        * A central space in which the organizer (or other participants when allowed) can share their screen. 

That's it for the moment :man_shrugging:

**Comment by dkgrieshammer** [comment]
Thanks for the Input, all points are converted into Issues to prioritize and this issue will be closed;
